name: "COMPOSITE" 
description: "test"

inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'

outputs:
  greeting:
    description: 'The greeting message'
    value: ${{ steps.greet.outputs.greeting }}

runs:
  # For more on composite actions, see:
  # https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
  using: composite
  steps:
    - name: greet
      shell: bash
      run: |
        echo "${{inputs.name}}"

