name: Common Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: |
          echo "Hello from reusable workflow"
          echo "Hello ${{ inputs.name }}"

      - name: Step 2
        run: echo "This is shared logic"
