name: Day 1 - Hello Workflow

on:
  workflow_dispatch:
    
jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello Sravan, CI/CD started!"

      - name: Verify runner
        run: |
         echo "Runner: $RUNNER_NAME"
         echo "OS: $RUNNER_OS"
         
      - name: Slack Success
        if: success()

        uses: slackapi/slack-github-actions@v2.1.0
        with:
         channel-id: ${{ secrets.SLACK_CID }}
         payload: |
              {
                "text": "✅ Job SUCCESS"
              }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
