name: Day 1 - Hello Workflow

on:
  workflow_dispatch:
    
jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello Sravan, CI/CD started!"

      - name: Verify runner
        run: |
         echo "Runner: $RUNNER_NAME"
         echo "OS: $RUNNER_OS"
         
      - name: Slack Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Pipeline Success"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
