name: Day 8 - SKC self learn

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Test"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      artifact_tags:
        description: "artifact"
        required: true
        

        
jobs:
  trail:
    runs-on: ubuntu-latest
    steps:
      - name: Randompick
        run: echo "hello ${{ inputs.artifact_tags}} and ${{inputs.environemnt}}" 
